### ISSUE TITLE
Last details

### ISSUE THREAD

**Issue by Serabe** [src-d/landing#103]
- [x] Remove arrow in hero in `sm` size. It is not useful given the size does not fit in the screen. 🔒 (@erizocosmico)
- [x] In mobile, in the lateral menu, the links needs to be the whole `li` so it is easier to tap. 🔒 (@erizocosmico)
- [x] In examples, the `< · · · >` for the slider needs to go to the bottom. 🔒 (@erizocosmico)
- [x] Visually remove the `hr` in projects when screen is small enough and check line height (maybe at those sizes the background could just disappear and would be easier). 🔒 (@erizocosmico)
- [x] Take into account pixel ratio when doing responsive. https://github.com/src-d/landing/issues/146
- [x] _view & apply_ buttons seems not vertically centered. Check line height and see if it is easily fixable. 🔒 (@erizocosmico)
- [x] In touch screens, distance between different links need to be bigger. This point refers to _x@sourced.tech_ and the _Looking for our PGP key?_. 🔒 (@erizocosmico)
- [x] Starting in 991px and lower, the two columns in in careers (the benefits part), need to be just one. 🔒 (@Serabe)
- [x] In secondary menus, clickable surface need to be a bit bigger. 🔒 (@erizocosmico)
- [x] Subpixel problem in cards headers.🔒 (@erizocosmico)
- [x] Remove posts section in pages. 🔒 (@Serabe)

**Comment by Serabe** [comment]
Remove posts section in pages #104

**Comment by Serabe** [comment]
Starting in 991px and lower, the two columns in in careers (the benefits part), need to be just one. #105

**Comment by erizocosmico** [comment]
Removing arrow https://github.com/src-d/landing/pull/106

**Comment by erizocosmico** [comment]
Navigation of the carousel below the terminal box https://github.com/src-d/landing/pull/107

**Comment by erizocosmico** [comment]
Bigger clickable surface on lateral menu links https://github.com/src-d/landing/pull/108

**Comment by erizocosmico** [comment]
Bigger clickable surface on secondary menu links https://github.com/src-d/landing/pull/109

**Comment by erizocosmico** [comment]
Increase distance between links in contact us section in footer https://github.com/src-d/landing/pull/110

**Comment by erizocosmico** [comment]
Vertically center view & apply btns https://github.com/src-d/landing/pull/111

**Comment by erizocosmico** [comment]
Fixed striked title in small sizes https://github.com/src-d/landing/pull/112

**Comment by erizocosmico** [comment]
@Serabe do we need the pixel ratio thing? It's already ok on a retina iPhone, for example:

![photo_2017-08-01_16-19-31](https://user-images.githubusercontent.com/1312023/28829807-4dd4b854-76d5-11e7-8bb2-0332cee1e6e7.jpg)

**Comment by erizocosmico** [comment]
Subpixel thingy https://github.com/src-d/landing/pull/113
