### ISSUE TITLE
Low-hanging fruits suggestions

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/landing#119]
I think we could do some tiny adjustments to visual design. What do you think @marnovo @Serabe ?

## Landing Page

- [x] source{d} logo could be smaller (height: 30px; margin-top: 12px;)
- [x] Font-size on main navigation could be adjusted (a = font-size: 18px; margin-top: 0; ul = margin-top: 10px;)
- [x] Main heading could be bolder (font-weight: 600;)
- [x] Slack logo on Join the Community block could be smaller (height: 50px; margin-top: 22px;)
- [x] The project's slider control icons could be smaller (arrow = background-size: 20px 20px; dots = height: 10px; width: 10px;)
- [ ] On "what developers say" we could user two columns instead of two rows
- [x] On "join the community" block before the footer the slack logo could be smaller (height: 46px; margin-top: 40px;)

## Projects

- [x] There could be some more positive space bellow the main headings (margin-bottom: 28px;)

**Comment by Serabe** [comment]
*Note*: I had to edit the comment since checking the boxes did not work for some random reason I'm not spending time on debugging.¯\_(ツ)_/¯

**Comment by Serabe** [comment]
Using two columns does not look good for a couple of our current tweets.
