### ISSUE TITLE
Healthcheck URL for api server

### ISSUE THREAD

**Issue by rporres** [src-d/landing#131]
Ideally it should be configurable, but due to https://github.com/kubernetes/ingress/issues/720 (we will use k8s GCE ingress) I'm basically interested in api server answering `200` to `GET /` requests

**Comment by marnovo** [comment]
@rporres what do you need exactly and from whom to unblock src-d/backlog#961?

**Comment by rporres** [comment]
I need landing-api server to return an `200` http response code to a `GET /` request. It currently returns a `404` response code

```
[GIN] 2017/08/23 - 10:04:34 | 404 |       3.603µs |        10.4.0.1 | GET      /
```

**Comment by marnovo** [comment]
Ok, Sergio said he'll look into this.
