### ISSUE TITLE
There should be no links pointing to sourced.tech but the hugo.baseurl

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#149]
Otherwise, that links will point to production instead of the same environment

**Comment by marnovo** [comment]
Might be related to the issue infra mentioned (https://github.com/src-d/backlog/issues/1068).
One example are the URLs from YAML files that define the links in the footer.

**Comment by dpordomingo** [comment]
It seems it is not related with src-d/backlog#1068 about docs.
The other one seems to be blocker for @src-d/infrastructure but this one it is not.
