### ISSUE TITLE
Pictures for Team people

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#152]
User story: _"As a developer of the Landing I need that all people images follows the original specs; I would appreciate if I could have a template for creating next images_"

Given the [original specs](https://docs.google.com/document/d/1gZ735i3G2t_nbLTWnBR69mXG0Wrkz7YMJ3ItjeNPteI/view#heading=h.wvjbaqoso28h)
> Circles are 75% of the block (and have a max-width of 200px) with white background, and a 5px #e8eced solid border. Images can ‘escape’ from the circles 20px above. - If this take much time, a possible solution would be to make the pictures not having this effect.
![image](https://user-images.githubusercontent.com/2437584/29966422-1c9f936c-8f12-11e7-9cf8-add6ace9bd43.png)

We need that all people pictures meets the same rule:
- size: 360x540px
- space above the head: 45px
- space above shoulders ~186px
- space above the wrists: ~465px

That measurements was based in Antonio's picture, that is the one who fits better the original especifications:

![antonio](https://user-images.githubusercontent.com/2437584/29971647-4736c07a-8f29-11e7-89ea-df6869d1c17f.png)

It would be great to have a kind of template to create new images.

It is needed to adjust &ndash;following the standard dimensions&ndash; the "new-guy" images:
- [new-man.png](https://github.com/src-d/landing/blob/master/static/img/people/placeholder/new-man.png)
- [new-woman.png](https://github.com/src-d/landing/blob/master/static/img/people/placeholder/new-woman.png)

Since we have not the original pictures the sources should be the current ones under [static/img/people](https://github.com/src-d/landing/tree/master/static/img/people) directory.
Because of that, and after the resizing/repositioning, I assume that some of them (Eiso, Máximo and Miguel, at least) will have extra transparent background below the waist, but it will not be a problem in the current `/team` page because the circle mask will hide that part.

**Comment by dpordomingo** [comment]
Once you have the new ones, you can make a PR against [release-v3 branch](https://github.com/src-d/landing/tree/release-v3)

**Comment by dpordomingo** [comment]
@ricardobaeta Once you have the new ones, you can make a PR against [release-v3 branch](https://github.com/src-d/landing/tree/release-v3), from a brand new branch created from there.

**PS:** issue description updated with a clarification

**Comment by ricardobaeta** [comment]
@dpordomingo I've somehow was not able to create a new branch. I'm commited the new photos #4eaf1e4b02043bd424bb6f131d12fe9a8a9224ec but I'm not able to push or make a new PR. Help needed :)

**Comment by dpordomingo** [comment]
^ solved irl

**Comment by dpordomingo** [comment]
@ricardobaeta I updated the issue description in order to have a clear "user story"

**Comment by marnovo** [comment]
@ricardobaeta we still need a template (and apply this template to any cases that aren't conforming).

**Comment by ricardobaeta** [comment]
- [x] Template https://drive.google.com/open?id=0Bzb_P4eXMOYFS3NuLS1fc1AzV0U
- [x] New Woman https://drive.google.com/open?id=0Bzb_P4eXMOYFMEg1aVlNcndFUFE
- [x] New Man https://drive.google.com/open?id=0Bzb_P4eXMOYFNGs1Z25HQTB0dkk
- [ ] Apply this template to any cases that aren't conforming

![man](https://user-images.githubusercontent.com/1746146/31951384-ddd4e3ec-b8d5-11e7-95ca-a0ce0db776fd.png)
![woman](https://user-images.githubusercontent.com/1746146/31951385-ddef45de-b8d5-11e7-8bdb-9611a5cfd1f1.png)

**Comment by dpordomingo** [comment]
I added the template to the project, so it will be available without going into Google Drive.
After the PR https://github.com/src-d/landing/pull/209 is merged, it will be under [/static/img/people/template/team-member-template.psd](https://github.com/src-d/landing/blob/master/static/img/people/template/team-member-template.psd)

**Comment by dpordomingo** [comment]
The placeholder images are already available at staging 
https://landing-staging.srcd.run
