### ISSUE TITLE
Top navigation vertical spacing is uneven, plus other quick fixes.

### ISSUE THREAD

**Issue by marnovo** [src-d/landing#161]
The top navigation bar looks fine in the original state…
<img width="1680" alt="screen shot 2017-10-09 at 3 07 17 pm" src="https://user-images.githubusercontent.com/15906764/31339609-b5e846d6-ad03-11e7-96d3-3c1558f13450.png">

…but when we scroll down the page, many sorts of problems arise:

<img width="1680" alt="screen shot 2017-10-09 at 3 07 33 pm" src="https://user-images.githubusercontent.com/15906764/31339617-ba3db478-ad03-11e7-91dc-d054d45fe5e7.png">

1. It is clearly unbalanced the spacing we have above (more) and below it the navigation bar items/logo (less). Looks very odd and I see no reason to be like this. Playing with the height numbers of the navbar content layer (60px -> 45px) and the background layer (75px -> 60px), it seems much more balanced.

2. One more thing is that the menu items font size seems a bit smaller than almost everything else in the page. 18px is the content description inside the cards—everything else is either 20px, or above. Eyeballing, 20px seems to fix the problem.

3. Last thing, when you scroll down you get a flat background (without any transition). Unless there's any advantage in terms of UX/UI, I'd go for keeping the same horizontal gradient we have in the original state before scrolling, since it looks pretty bleak when compared to the vivid gradients of the other parts of the site.

4. Extra: Another thing is that if you look at the vertical alignment, the logo is slightly higher than the menu items menu. Just a few pixels…

5. Extra 2: not sure about how this works better, but seems all the website content basically uses slight or no bold fonts. The bold navbar menu items work well with the logo, but maybe too strong vs. anything else in the page. Not sure about this one, just food for thought.

Given all points 1-4, this is how it looks when fixed (IMO way better in usability + aesthetics):

<img width="1680" alt="screen shot 2017-10-09 at 3 18 57 pm" src="https://user-images.githubusercontent.com/15906764/31340276-ed8c775e-ad05-11e7-8140-304af55b95d3.png">

Given also point 5, this is how it looks like:

<img width="1680" alt="screen shot 2017-10-09 at 3 18 57 pm - not bold" src="https://user-images.githubusercontent.com/15906764/31340580-e983fece-ad06-11e7-9800-496361268f98.png">

@ricardobaeta what do you think?

**Comment by marnovo** [comment]
P.s.: @dpordomingo site launch is still a much higher priority than these small quirks. If possible before, nice, otherwise it's ok to fix the following week.

**Comment by ricardobaeta** [comment]
![image](https://user-images.githubusercontent.com/1746146/31340932-15c67812-ad08-11e7-8e4a-908169c73856.png)

**Comment by marnovo** [comment]
@ricardobaeta this was always a though choice: to align for the inner content (text) or the outer content (text + padding/highlight when selected? To me either work, couldn't reason why one would be much better than the other… can you? Anyhow the things I pointed at seem less ambiguous and more important, would like your thoughts on them as well.

**Comment by ricardobaeta** [comment]
@marnovo 

> to align for the inner content (text) or the outer content (text + padding/highlight when selected

If we align the logo left, we have to align the navigation right.

> Anyhow the things I pointed at seem less ambiguous and more important, would like your thoughts on them as well.

I gave you a 👍 on this! Thanks :)
