### ISSUE TITLE
Footer social media icons don't show on mobile

### ISSUE THREAD

**Issue by marnovo** [src-d/landing#165]
Footer social media icons don't show on mobile

Screenshot:
![screenshot_20171012-120314_01](https://user-images.githubusercontent.com/15906764/31512373-fae8bb9c-af8a-11e7-8a6b-fdf42c54ee4b.jpg)

**Comment by marnovo** [comment]
@eiso are you still having this problem? Could be migration-related problem.

**Comment by eiso** [comment]
No works well now.
