### ISSUE TITLE
Documentation on content-related files and available fields/effects

### ISSUE THREAD

**Issue by marnovo** [src-d/landing#174]
We need to create proper documentation on the list of all files and folders related to the landing content and available fields/options available in the YAML and MD files, so that whoever wants/needs to update it not only can understand where to look and how to do it, but also doesn't break anything midway.

**Comment by dpordomingo** [comment]
The scope of this issue was redefined by https://github.com/src-d/backlog/issues/1078

**Comment by dpordomingo** [comment]
waiting for https://github.com/src-d/landing/pull/226 validation
