### ISSUE TITLE
Bug in safari when accessing team page

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#180]
As reported by @ricardobaeta the team page does not look ok in safary

![image](https://user-images.githubusercontent.com/2437584/31628560-5a322740-b2b1-11e7-94cd-7dd451ce0917.png)

**Comment by ricardobaeta** [comment]
iPhone SE, Safari iOS 11.0.3

**Comment by dpordomingo** [comment]
@marnovo @ricardobaeta We can do graceful degradation in Safari as a quick fix, and provide a proper fix after the release.
That way the Safari users will not see the awful circle bug.

It can already be validated in staging http://landing-staging.srcd.run/team/
![image](https://user-images.githubusercontent.com/2437584/31646820-7ab7191e-b304-11e7-93a0-7b9e9ee0bb84.png)

If you agree, it would be merging the PR https://github.com/src-d/landing/pull/181

**Comment by marnovo** [comment]
Approved, let's keep this open until we actually fix it.
