### ISSUE TITLE
"A" should be lower case... I would also replace ; with :

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#185]
![image](https://user-images.githubusercontent.com/2793551/31653821-3eb0585c-b324-11e7-9ca2-6f09cafd5134.png)

**Comment by marnovo** [comment]
PRs are welcome. :)

**Comment by dpordomingo** [comment]
It'll be deployed to prod once @marnovo validates the PR https://github.com/src-d/landing/pull/209 already deployed into staging
https://landing-staging.srcd.run
