### ISSUE TITLE
Mention "big code" anywhere?

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#187]
We definitely work with "big code" so can be nice to mention somewhere.

**Comment by marnovo** [comment]
Why and where?

**Comment by vmarkovtsev** [comment]
Because it reads cool; somewhere in our descriptions, e.g. What we do or Eiso's words

**Comment by jbeardly** [comment]
From my side I prefer avoid any reference to big data.

**Comment by vmarkovtsev** [comment]
*Sigh*

**Comment by vmarkovtsev** [comment]
Wow, Veselin thinks the same https://github.com/learnbigcode/learnbigcode.github.io

**Comment by bzz** [comment]
Big Code is mentioned in few papers as "strategy" of ZTH group
