### ISSUE TITLE
"buy you any books" leads to traveling expenses

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#190]
This is somewhat confusing.

![image](https://user-images.githubusercontent.com/2793551/31654319-fe537f30-b325-11e7-8b97-25be3cc7df60.png)

**Comment by marnovo** [comment]
It links to the page that has our expense policy (and all it covers), including book buying:
https://github.com/src-d/guide/blob/master/general/expenses_travel.md

Adding the #what-expenses-will-sourced-reimburse means it would very soon break once header text is changed.

@dpordomingo please close this.
