### ISSUE TITLE
Twitter testimonial has unprintable emoji

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#193]
![image](https://user-images.githubusercontent.com/2793551/31663330-f2f3061c-b341-11e7-8d24-38e8c0c6ffed.png)

Note the rectangles. Can be a problem with my system font... Should we load a bulletproof one?

**Comment by marnovo** [comment]
What is your OS, browser, etc.?
Can you check what font is being actually rendered? Like using: http://www.chengyinliu.com/whatfont.html

macOS 10.12.6, Chrome/Safari:
![screen shot 2017-10-20 at 8 05 45 pm](https://user-images.githubusercontent.com/15906764/31835503-1c444f20-b5d2-11e7-9579-a5ac67c7d0c1.png)
