### ISSUE TITLE
Photos: not the same height

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#199]
My perfectionist in me cries bloody tears:

![screenshot from 2017-10-18 08-25-54](https://user-images.githubusercontent.com/2793551/31703772-6d96e838-b3de-11e7-88bf-36dde8662626.png)

**Comment by ricardobaeta** [comment]
@dpordomingo Any help from my side on this?

**Comment by dpordomingo** [comment]
nope, many thanks @ricardobaeta !! :D

**Comment by dpordomingo** [comment]
It'll be deployed to prod once @marnovo validates the PR https://github.com/src-d/landing/pull/209 already deployed into staging
https://landing-staging.srcd.run
