### ISSUE TITLE
Provide id for "perks and benefits"

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#200]
"Perks and benefits" section's h1 does not have an id and it is impossible to reference it (and I will definitely want to reference!)

![image](https://user-images.githubusercontent.com/2793551/31703875-ed090876-b3de-11e7-8ef3-b36f5d66baf4.png)

**Comment by marnovo** [comment]
Request makes sense (also for other ids); will add to the backlog and will solve it in two steps.

**Comment by dpordomingo** [comment]
Once it has been merged and deployed, the link will be:
https://sourced.tech/careers/#benefits

**Comment by dpordomingo** [comment]
It'll be deployed to prod once @marnovo validates the PR https://github.com/src-d/landing/pull/209 already deployed into staging
https://landing-staging.srcd.run

**Comment by marnovo** [comment]
> Once it has been merged and deployed, the link will be:
> https://sourced.tech/careers/#benefits

@vmarkovtsev

**Comment by vmarkovtsev** [comment]
thanks
