### ISSUE TITLE
Slack form does not work at all in iPhone 7

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#212]
He is not able to see any of the slack forms since the redesign was launched.

iOS 10.2, in Chrome and Safary.

Reported by @rporres irl

![image uploaded from ios](https://user-images.githubusercontent.com/2437584/32049116-1c9917de-ba4c-11e7-88b3-0e8e5d8ff7be.png) ![image uploaded from ios 1](https://user-images.githubusercontent.com/2437584/32049206-7734c526-ba4c-11e7-8742-dc7c05983a51.png)

**Comment by dpordomingo** [comment]
I can not reproduce this bug

**Comment by rporres** [comment]
I've asked a friend and it looks fine in a regular iPhone 6

**Comment by eiso** [comment]
@rporres is this still the case on your device?

**Comment by rporres** [comment]
Yes it is. I've only found people around me with iPhone 6 or lower, where it is not reproduced.
