### ISSUE TITLE
Follow src-d/ci/Makedile.main conventions

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#216]
As it was pointed out by @rporres by https://github.com/src-d/blog/pull/146#discussion_r148014089 the `landing/Makefile` should import and follow [src-d/ci/Makedile.main](https://github.com/src-d/ci/blob/master/Makefile.main) conventions.

copied from https://github.com/src-d/blog/issues/150

**Comment by vcoisne** [comment]
is there any action for us to take here @dpordomingo ?

**Comment by dpordomingo** [comment]
I think it's not an urgent thing, but something to consider when we have some time to spend improving the deployment.
I remember that @meyskens also mentioned some possible improvements that could be made in Landing. Could you provide some info about your suggestions Maartje?

**Comment by meyskens** [comment]
Few improvements infra whise:
* move the helm chart to src-d/charts
* move the Helm deploy to Travis CI using the included scripts in src-d/ci

**Comment by rporres** [comment]
> move the helm chart to src-d/charts

Since this is not reusable by anyone else, it could be ok to have it here but it's necessary to 

> move the Helm deploy to Travis CI using the included scripts in src-d/ci

due to the way our Travis CI integration works

**Comment by vcoisne** [comment]
@rporres I let you make the decision on whether or not you want to improve this and when since it would be done by your team.

**Comment by rporres** [comment]
Both things make a lot of sense. I will create issues for that as we should be removing Drone.

**Comment by vcoisne** [comment]
@rporres closing this issue given that I think you completed the move to Travis.
