### ISSUE TITLE
Adding Francesc to the management team section

### ISSUE THREAD

**Issue by eiso** [src-d/landing#218]
Adding Francesc to the management team section: https://sourced.tech/team/

@marnovo if you're feeling better can you take the photo of @campoy tomorrow, otherwise ask someone to do so the following Friday.

**Comment by dpordomingo** [comment]
I think he was already added:
![image](https://user-images.githubusercontent.com/2437584/36846516-48705f3a-1d5b-11e8-90b0-a9243eb90a03.png)
Feel free to reopen if any change is yet needed :dagger:
