### ISSUE TITLE
Update team page considering new people and teams

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#227]
- Carlos (Senior Software Engineer at Apps) https://github.com/carlosms
- Maxim (Senior Software Engineer at Apps) https://github.com/smacker
- Denys Smirnov (Senior Software Engineer at LA) https://github.com/dennwc
- Romain Keramitas (Software Engineer Intern at ML) https://github.com/r0mainK

**Comment by ricardobaeta** [comment]
@marnovo Will we be taking pictures?
