### ISSUE TITLE
Change Anna's title from Operations to Talent Manager

### ISSUE THREAD

**Issue by jorgeschnura** [src-d/landing#241]
Anna's official title is Talent Manager, but she's currently shown as Operations

**Comment by dpordomingo** [comment]
the role was taken from https://github.com/src-d/backlog/issues/1236#issue-301478428
It will be updated by https://github.com/src-d/landing/pull/242

**Comment by dpordomingo** [comment]
@jorgeschnura the  @tsolakoua role was updated and deployed https://sourced.tech/team

**Comment by tsolakoua** [comment]
@jorgeschnura , we had agreed with @eiso to change my title from Talent Manager to Operations which seems representative as well, at least temporarily until we find a better one for personal career reasons. Taking that into consideration, I would like to change it back to Operations if possible.

**Comment by dpordomingo** [comment]
It's easy to rollback or update (2min work), so just ping me when you agree on something :D
