### ISSUE TITLE
CI isn't working as desired

### ISSUE THREAD

**Issue by eiso** [src-d/landing#245]
Desired behavior:

Staging:

1. Merge a PR to the landing repo
2. See the changes on our staging site

Production:

1. Merge a PR to the landing repo
2. Create a new release
3. See the new changes on sourced.tech
---------

Currently, I've tried the staging steps, while the build passes, no changes are seen on the staging site.

This is **HIGH** priority since we'll are currently working on the new site but don't want to have to bother the applications team.

Tagging @smola here since he recommended I post this as an issue here.

**Comment by rizome** [comment]
@eiso as explained at https://github.com/src-d/guide/blob/master/engineering/continuous-delivery.md Staging is deployed every time Staging branch is updated.
To see your changes at staging env you can push to `sourced:staging`

**Comment by eiso** [comment]
Awesome, and to update production, is there a branch?

**Comment by dpordomingo** [comment]
Every time you release a new version, it is deployed into Prod.
It happens the same for landing, blog and talks.

**Comment by eiso** [comment]
Thank you!

**Comment by eiso** [comment]
Leaving this here: https://github.com/src-d/issues-infrastructure/issues/185

**Comment by bzz** [comment]
Shall we close this, if it was addressed @eiso and it works for you now, or is there anything left?

**Comment by bzz** [comment]
Closing as it seems to be resolved.

But please, do not hesitate to re-open if that is not the case!
