### ISSUE TITLE
Clickable Card on Open Source Projects 

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/landing#272]
We need to add a behavior so that people can click on Open Source projects in the OSS pages for example in the text/title/card, no just in the github icon.

**Comment by tmott13** [comment]
Hi @ricardobaeta ,

I re-created this issue in JSFiddle and this is the solution I came up with:

`<div class="row highlight-cards mb-4">
  <div class="col-lg-4 mb-4 mb-lg-0">
    <a href="https://doc.bblf.sh/" target="_blank">
      <div class="card text-white orange h-100">
        <div class="card-body p-5">
          <i class="ic icon-git text-white"></i>
          <p class="card-intro mb-0">Code Analysis</p>
          <h3 class="title-line line-yellow">Babelfish</h3>
          <p>Babelfish is a self-hosted server for source code parsing. It can parse any file, in any supported language, extracting an Abstract Syntax Tree (AST) from it and converting it into a Universal Abstract Syntax Tree (UAST).</p>
        </div>
      </div>
    </a>
  </div>
  <div class="col-lg-4 mb-4 mb-lg-0">
    <a href="https://github.com/src-d/go-git" target="_blank">
      <div class="card text-white orange h-100">
        <div class="card-body p-5">
          <i class="ic icon-git text-white"></i>
          <p class="card-intro mb-0">Code Retrieval</p>
          <h3 class="title-line line-yellow">go-git</h3>
          <p>go-git is a highly extensible Git implementation in pure Go language</p>
        </div>
      </div>
    </a>
  </div>
  <div class="col-lg-4">
    <a href="https://github.com/src-d/gemini" target="_blank">
      <div class="card text-white orange h-100">
        <div class="card-body p-5">
          <i class="ic icon-git text-white"></i>
          <p class="card-intro mb-0">Code Analysis</p>
          <h3 class="title-line line-yellow">Gemini</h3>
          <p>Gemini is a tool for searching for similar ‘items’ in source code repositories. Supported granularity level or items are: repositories, files and functions.</p>
        </div>
      </div>
    </a>
  </div>
</div>`

This is a working solution, the GitHub icon will just be an icon since the entire card will be hyperlinked.

If this change is okay with you, I can create a pull request.

Thanks!

**Comment by marnovo** [comment]
Hi @tmott13, let's keep the discussion going though the [PR review](https://github.com/src-d/landing/pull/288). Thanks. :)

**Comment by dpordomingo** [comment]
Many thanks @tmott13 for the fix merged via https://github.com/src-d/landing/pull/309!
