### ISSUE TITLE
Out of sync sass and generated css

### ISSUE THREAD

**Issue by carlosms** [src-d/landing#274]
PR #268 changed a css file directly instead of updating the source sass and generating the result.
The files are now out of sync.

For reference, the correct way would be:
- Install sass: https://sass-lang.com/install
- generate css from scss:
```bash
cd static/scss
sass style.scss style.css
```

Ideally the CI would catch this problem. Or we would not commit the css files and they would be generated on the build step.

cc @ricardobaeta

**Comment by eiso** [comment]
@ricardobaeta can you please make a PR to update the SASS for #268, so that I can generate the css from sass and release.

**Comment by ricardobaeta** [comment]
Sorry about this Eiso, https://github.com/src-d/landing/pull/277 

Thanks @carlosms for the catch!

**Comment by eiso** [comment]
Fixed and deployed to staging (and will be in the next RC).
