### ISSUE TITLE
New roles don't get published on our website 

### ISSUE THREAD

**Issue by tsolakoua** [src-d/landing#282]
related to #310

- I noticed yesterday that the new published positions ([Lead](https://hire.lever.co/jobs/postings/edit/5b7d11dd-03ce-4d61-a00a-ff91ae1ec270?view=all&status=published) and [QA](https://hire.lever.co/jobs/postings/edit/8e4c4c54-096a-4050-9882-6ae1ca71d8a0?view=all&status=published)) are not shown on our landing page.  
- They are definetely published on [Lever](https://jobs.lever.co/sourced/).
- When I tried to make Data Retrieval role unpublished as an experiment, it was still on our website. 
- I'm not sure where the error comes from (maybe on ```hugo/layouts/company/single.html ```?), I am trying to figure it out myself through the code, but I post it here as it would be nice to be solved as soon as possible, as both roles need candidates asap.

Update: after discussion on Slack, it seems that Lever integration wasn’t added yet to the new site.

**Comment by carlosms** [comment]
PR #284 is a workaround with a manual update of the job openings.
Let's keep this issue open to add the integration with lever when we have some more time.

**Comment by dpordomingo** [comment]
The PR https://github.com/src-d/landing/pull/322 is ready to be validated :D
Already deployed into staging https://landing-staging.srcd.run/community

**Comment by tsolakoua** [comment]
Thank you @dpordomingo 🥇
