### ISSUE TITLE
Correction on source{d} svg logo artifact

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/landing#283]
As we can see by the image bellow, the current svg source{d} logo has some strange vector artifacts.

![image](https://user-images.githubusercontent.com/1746146/46079228-cf2eb500-c196-11e8-90a5-23950af86d54.png)

**Comment by ricardobaeta** [comment]
Hi @dbeezt ! Thanks for caring! We're actually working on this. You can see the updated logo in our [source{d} Media Kit](https://github.com/src-d/artwork/blob/master/media-kit/README.md). We'll soon update it on the website.

**Comment by dpordomingo** [comment]
I think it no longer happens in our current site, does it?
