### ISSUE TITLE
Favicon issues on chrome, safari, firefox

### ISSUE THREAD

**Issue by aliciakozlowski** [src-d/landing#308]
Despite the favicon showing up in a google search, when you use Google Chrome or Firefox the source{d} favicon is nonexistent 
Shown (in chrome): 
<img width="226" alt="screen shot 2018-10-31 at 13 25 35" src="https://user-images.githubusercontent.com/43578215/47788032-e2422100-dd10-11e8-9a74-e8c056756960.png">

I checked Safari to see the status and it shows as a generic "S" and not the appropriate source{d} version.
Shown (in safari):
<img width="601" alt="screen shot 2018-10-31 at 13 26 00" src="https://user-images.githubusercontent.com/43578215/47788186-4369f480-dd11-11e8-9600-5ff3b6acf4ae.png">

**Comment by dpordomingo** [comment]
Fixed by https://github.com/src-d/landing/pull/312
@aliciakozlowski you should be able to validate the fix at staging https://landing-staging.srcd.run ; does it suit you?
