### ISSUE TITLE
New blog posts don't get published on our website

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#310]
related to #282

After the redesign, the latest blog posts are no longer published in our landing.
Should this feature be restored?

**Comment by dpordomingo** [comment]
I just assigned this question to @campoy and @marnovo, but since @eiso was also involved in the development of the redesign, he might be also interested in this issue.

**Comment by marnovo** [comment]
> Should this feature be restored?

Most definitely yes.

**Comment by campoy** [comment]
Yes, please. Let's fix this.

**Comment by dpordomingo** [comment]
The PR https://github.com/src-d/landing/pull/322 is ready to be validated :D
Already deployed into staging https://landing-staging.srcd.run/community

**Comment by campoy** [comment]
I would expect https://landing-staging.srcd.run/ to show the latest blog post, right?
Instead I see the PGA announcement

**Comment by dpordomingo** [comment]
I'm seeing the "splitting millions of &hellip;" blog post in:
- last post in our blog https://blog.sourced.tech/
- first card in production https://sourced.tech/
- first card in staging https://landing-staging.srcd.run/

Could it be a problem with your browser cache?

**Comment by campoy** [comment]
Oh, I misunderstood what you meant by latest update!

Ok, so this issue is fixed 🎉 and I created a new one to update the PGA announcement to something more relevant #325.
