### ISSUE TITLE
favicon.ico not working

### ISSUE THREAD

**Issue by campoy** [src-d/landing#314]
Visited our website on Chrome for Mac Version 71.0.3578.20

favicon.ico did not display on any of the pages, as snapshots show

<img width="331" alt="screen shot 2018-10-31 at 9 02 14 pm" src="https://user-images.githubusercontent.com/2237452/47831984-43d5b000-dd50-11e8-8f28-47abf0b4232b.png">

<img width="264" alt="screen shot 2018-10-31 at 9 02 03 pm" src="https://user-images.githubusercontent.com/2237452/47831981-40dabf80-dd50-11e8-889e-d9fc48bf0782.png">

**Comment by dpordomingo** [comment]
duplicated https://github.com/src-d/landing/issues/308

**Comment by dpordomingo** [comment]
it's already in prod :D

**Comment by campoy** [comment]
That's not the good one, though. Don't we have one that matches the new branding guidelines?

**Comment by dpordomingo** [comment]
I just recovered the previous one.
I was not aware of new branding guidelines, I'll ask about that, and update it.

**Comment by campoy** [comment]
@ricardobaeta should know about this,thanks!
