### ISSUE TITLE
Move pills from line-height to padding.

### ISSUE THREAD

**Issue by Serabe** [src-d/landing#32]

**Comment by marnovo** [comment]
@Serabe is this still relevant? If so, can you please help us understand it? Thank you!

**Comment by Serabe** [comment]
Only if pills will have more than one line. The vertical alignment is done via line-height. For more than one line, it needs to be moved to use vertical padding.

**Comment by dpordomingo** [comment]
@Serabe If I understood you, you're talking about the following:
![image](https://user-images.githubusercontent.com/2437584/30036532-93fb989e-91b4-11e7-9d35-47d9536e7ed5.png)
Many thanks for the clarification !!!!!

**Comment by Serabe** [comment]
Nope, about button pills.

**Comment by marnovo** [comment]
@ricardobaeta can you check whether this case happens at any point in our landing/blog? Thanks.

**Comment by ricardobaeta** [comment]
@marnovo Yes it does and I believe the pills should be aligned with horizontal center alignment on first line. like a bullet.

**Comment by dpordomingo** [comment]
But... did it happened? Wich resolution/device?
Could you provide a screenshot to spot the place where it appeared?

**Comment by ricardobaeta** [comment]
@dpordomingo Sorry, it's ok now. I didn't noticed before.

![image](https://user-images.githubusercontent.com/1746146/31938313-28ec7b96-b8af-11e7-99b1-4dc95dc199e3.png)

**Comment by dpordomingo** [comment]
So... we didn't found any problem... right?

**Comment by ricardobaeta** [comment]
Yes. We can close this.
