### ISSUE TITLE
Change `NEW` announcement to point to the Engine video post

### ISSUE THREAD

**Issue by campoy** [src-d/landing#325]
I would like to update the announcement banner on the landing from PGA (shown below)

<img width="656" alt="screen shot 2018-11-14 at 12 11 56 pm" src="https://user-images.githubusercontent.com/2237452/48509650-8abead80-e806-11e8-87aa-80d41274cd61.png">

to a link to the blog post we wrote presenting the video for the engine.

The announcement should read something like "Watch a 5 minutes video to understand how the engine works" and point to https://medium.com/sourcedtech/source-d-engine-in-5-minutes-6b3b19789594.

**Comment by dpordomingo** [comment]
(a) Should the NEW section retrieve content automatically from somewhere (like «latest updates» or «job offers» section)?
(b) Or is that section static and should it be edited > PR > released/deployed?

If it's (a), from where?
If it's (b) —I'd vote for it— it's easier: I'd load its contents from a new subkey under [hugo.config.yaml::params](https://github.com/src-d/landing/blob/master/hugo.config.yaml#L36)
```yml
  new:
    title: #link text
    url: #link url
```
quick and dirty, and it would make the changes easier to be done, reviewed and merged.

**Comment by campoy** [comment]
I'm happy with b, as long as it's easy to change over time.

**Comment by dpordomingo** [comment]
ready to be merged/deployed https://github.com/src-d/landing/pull/327 ;)

**Comment by dpordomingo** [comment]
already at prod
:dancer:
