### ISSUE TITLE
Links to landing pages should point to https URLs

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#329]
- [x] On https://sourced.tech/community/#resources link to newsletter should be https://go.sourced.tech/newsletter
- [x] On https://sourced.tech/  "request a demo" buttons in the header and bottom Call to Action should point to https://go.sourced.tech/engine
- [ ] On https://sourced.tech/lookout/ "Sign up" button should be "Request a demo" and point to https://go.sourced.tech/lookout/

**Comment by vcoisne** [comment]
Ping @marnovo

**Comment by dpordomingo** [comment]
I think that the 2nd one is addressed by https://github.com/src-d/landing/pull/340

**Comment by marnovo** [comment]
First two are done and the link of the 3rd is fixed, just missing renaming the Lookout page button from `Sign Up` to `Request Demo` making it analogous to the Engine page.
