### ISSUE TITLE
Clarify call to action and relevant links on the Lookout landing page

### ISSUE THREAD

**Issue by creachadair** [src-d/landing#332]
From https://github.com/src-d/empathy-sessions/issues/31.

The landing page for lookout does not currently contain links to developer-oriented instructions. On https://sourced.tech/lookout/, the calls to action are

1. Request a demo (leads to a contact form),
2. Install Engine (not the same product),
3. Sign up for the beta (a forward jump to another button, that leads to a contact form).

Although the top nav does point to source{d}'s more general outlook on open source, the page does not point to the [GitHub repo for lookout](http://github.com/src-d/lookout), nor to any of the "getting started" documentation found there. It would be helpful to include some more specific pointers, so that developers wanting to dig into lookout firsthand will have something to chase.

**Comment by dpordomingo** [comment]
that's true!
I'll purpose a change in the section where `engine` is linked instead of `lookout` (because it is the `lookout` landing page!! :scream: )
Maybe @src-d/product could consider your other suggestions about helping the developers to reach our lookout code/docs.

**Comment by dpordomingo** [comment]
I reviewed your point `2`, and there is a reason for that:

>**all the pages in our landing ends the same way:**
>- _&laquo;try engine&raquo; banner_
>- page footer

It make sense to change it to announce **source{d} Lookout** in its own landing page, but it should be approved by @src-d/product

**Comment by vcoisne** [comment]
Not relevant anymore, that page is going away.
