### ISSUE TITLE
Buttons in careers page not aligned 

### ISSUE THREAD

**Issue by tsolakoua** [src-d/landing#337]
It seems that the "View and Apply" buttons are not aligned properly - check Senior product manager, Senior Test Engineer 

<img width="895" alt="screenshot 2018-12-17 at 5 48 42 pm" src="https://user-images.githubusercontent.com/15012967/50101929-20919200-0224-11e9-9287-38d761fc955e.png">

**Comment by dpordomingo** [comment]
In the current design/layout, the buttons depend on the content height, so different role names impact on them.
Since it was coded that way during the redesign, @ricardobaeta should confirm if it was on purpose or something unexpected.

**alternative**: align the button to the bottom of the card

**Comment by tsolakoua** [comment]
@dpordomingo thanks! I think a few weeks ago it didn't seem like that or at least it was and I didn't notice.

**Comment by dpordomingo** [comment]
The css didn't change. The "issue" was not noticed before, because at that moment the offers were sorted in a way that all cards in the same row had the same `offer.title` size; at some point, it was added a new job offer, and the rows were not grouped that way.
Now, the jobs are fetched from Lever, so the order is defined by them; what we need is to align the button to the bottom if it is a problem :wink:

**Comment by tsolakoua** [comment]
In my opinion, it's something should be changed if possible as it doesn't look very nice but the final decision should be taken by @ricardobaeta as it's a design related issue.

**Comment by ricardobaeta** [comment]
@dpordomingo This is something we can address firstly in the [source{d} UI Pattern Library](https://github.com/src-d/design/blob/master/ui-pattern-library/README.md)?

**Comment by dpordomingo** [comment]
It seems to be already in the shared sketch file, so it seems to be a bug when the layout was implemented.
![image](https://user-images.githubusercontent.com/2437584/51176235-b15b9c00-18bc-11e9-8213-15048c4df02c.png)
Thanks for sharing.

**Comment by vcoisne** [comment]
@znegrin Please take a look into this once bug when you get a chance?

**Comment by znegrin** [comment]
This is now fixed on https://github.com/src-d/landing/pull/455

**Comment by znegrin** [comment]
This is now on production: [v4.17.10](https://github.com/src-d/landing/releases/tag/v4.17.10)
