### ISSUE TITLE
Update Dependent Files in CONTRIBUTING.md

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#355]
caused by https://github.com/src-d/product/issues/365

[**Dependent Files**](https://github.com/src-d/landing/blob/master/CONTRIBUTING.md#dependent-files) section in `CONTRIBUTING.md` should be updated considering changes made by https://github.com/src-d/product/issues/365

**Comment by vcoisne** [comment]
@dpordomingo Updated here https://github.com/src-d/landing/pull/449

Please merge if it looks good to you.
