### ISSUE TITLE
Replace text with logos for Engine & Lookout Pages

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/landing#365]
Following our [Brand Guidelines](https://docs.google.com/presentation/d/1q290ZrAMola1nSwzYmScOo3gsMgEIXKi2BsWgnMY078/edit#slide=id.g4622ee0749_3_11), we should replace the textual designation of the Engine & Lookout on their Product Pages, for their logos.

**Website**

![image](https://user-images.githubusercontent.com/1746146/53416782-17fbcb80-39cc-11e9-9c0f-7d828ef76943.png)

**Brand Style Guide**

![image](https://user-images.githubusercontent.com/1746146/53416954-745eeb00-39cc-11e9-95a3-25bf2e21be90.png)

Steams from: https://github.com/src-d/product/issues/287#issuecomment-465634164

**Comment by dpordomingo** [comment]
I'd try something like:
```html
<header class="text-center">
    <h2 class="subtitle text-green">Product</h2>
    <img src="PATH_TO_LOGO" width="..." height="..." alt="source{d} Engine" />
</header>
```
For simplicity.

But not a SEO nor accessibility expert.

**Comment by ricardobaeta** [comment]
@dpordomingo Already PR'd here https://github.com/src-d/landing/pull/369

**Comment by vcoisne** [comment]
Not relevant with new branding / naming.
