### ISSUE TITLE
I cannot copy text of the office address

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#370]
from https://sourced.tech/company/
![Screenshot 2019-03-13 at 13 12 04](https://user-images.githubusercontent.com/2793551/54278022-9f7f3800-4591-11e9-9418-bda4452f5650.png)

I cannot select the text and copy it. As soon as I click, I go to Google Maps.

**Comment by dpordomingo** [comment]
You're right @vmarkovtsev 
@ricardobaeta could you provide an alternative?

idea:
- to attach the gmaps behavior to a visual element (a map, a magnifier icon...), so the user will know that clicking in that item will open something. That way, text will be text, and icons will trigger actions.

workaround @vmarkovtsev 
- you can copy text if during the selection process you perform the `mouseup` outside of the box :wink:

**Comment by vcoisne** [comment]
Looks like this was fixed.

**Comment by dpordomingo** [comment]
Not yet. If you try to select an address, the selection is replaced by a map when you perform the mouseup

**Comment by vmarkovtsev** [comment]
cc @vcoisne

**Comment by vcoisne** [comment]
I tried to copy / paste and it worked but I see what you mean @vmarkovtsev. @znegrin can you follow @dpordomingo suggestion here above ?

**Comment by znegrin** [comment]
This is now on production: [v4.17.9](https://github.com/src-d/landing/releases/tag/v4.17.9)
