### ISSUE TITLE
Update architecture diagram picture on home

### ISSUE THREAD

**Issue by marnovo** [src-d/landing#378]
Now that we have an updated and much better version of the architecture (Code as Data + ML on Code) diagram (see https://github.com/src-d/backlog/issues/1385#issuecomment-483645134), it's time to update it on the landing with any adjustments necessary to make web-friendly.

**Comment by ricardobaeta** [comment]
Hi @marnovo the solution we're crafting has in mind desktop and mobile behavior for enhanced legibility. Having this in mind, we're going to have two images, the first one will be for desktop - horizontal layout - and the second one for mobile - vertical layout. With a css media query, we're going to hide & display each image.

Does it look good?

*Desktop*

![image](https://user-images.githubusercontent.com/1746146/56286849-ad852300-6112-11e9-8897-2554b6021ce9.png)

*Mobile*

![image](https://user-images.githubusercontent.com/1746146/56286873-bf66c600-6112-11e9-8ee8-1d5968ed18c7.png)

/cc @dpordomingo

**Comment by marnovo** [comment]
@ricardobaeta yes that works fine.

**Comment by ricardobaeta** [comment]
Update: [PR'd](https://github.com/src-d/landing/pull/379).

**Comment by ricardobaeta** [comment]
Update: [Merged](https://github.com/src-d/landing/pull/379).

> closing this per objective accomplishment.
