### ISSUE TITLE
Uncontrolled scroll on indexed carousels

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#391]
described by https://github.com/src-d/landing/pull/390#issuecomment-494394007

Anchor links for tabs for carousels conflicts with an ancient hack for scrolling to anchors. :boom: 

When one carousel contains tabs containing links with anchors, every time you click in one tab, the scroll is magically moved up and down in a weird way.

**Comment by vcoisne** [comment]
@dpordomingo I believe this is fixed. Correct ?

**Comment by dpordomingo** [comment]
Not sure. It was a problem with our JS, and how we use tabs and carousels.
The problem could have disappeared in our current landing because I think we no longer have these interactions between tabs and carousels... but if they're added in the future, the problem will reappear.

So it's up to you if you prefer to leave this issue opened as a sort of documentation of a latent problem, or close it because not affecting landing right now.

**Comment by vcoisne** [comment]
Thanks for the context. Let's close for now.
