### ISSUE TITLE
Fix line-height

### ISSUE THREAD

**Issue by Serabe** [src-d/landing#41]
Move from length to number

**Comment by marnovo** [comment]
@Serabe is this still relevant? If so, could you please help us understand it? Thanks!

**Comment by Serabe** [comment]
Yes. A `line-height` of 1.2 means 1.2em in the element being applied to, while 1.2em means 1.2em of the element in which is being defined.

This causes having strange variables like _small line-height_ and _big line-height_ having the same value.
