### ISSUE TITLE
Company page updates

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#414]
@znegrin please make the following edits to the company page:

- Under roadmap replace “[…] as well as a single one through our powerful source{d} Engine and machine learning tools.” By  "[…] as well as a single one through our powerful source{d} platform and machine learning tools.”
- Remove all teams & photos, keep only Management section
- Remove “CAREERS, Job Opportunities Exceptional missions require exceptional people; we know that.If our challenges excite you and you want to help us to pave the future road towards machine learning on source code, check where you fit best from our current openings or drop us a message.”
- Remove “download engine” and “Newsletter” sections

**Comment by vcoisne** [comment]
@znegrin Also please update the Page title from "An exceptional mission executed by exceptional people" to " We empower IT executives to be data-driven leaders"

**Comment by znegrin** [comment]
I updated the page here: #428
