### ISSUE TITLE
List of issues currently in staging

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#424]
Thanks a lot @znegrin for all your hard work. We're almost there :) 

Please fix the following issues currently in staging:

## Homepage :

- [x] Switch illustrations for Engineering Effectiveness & Cloud Native DevOps Transformation
- [x]  Update each "Learn More" links to point to their respective Solution page  
<img width="1197" alt="Screen Shot 2019-06-25 at 8 00 53 PM" src="https://user-images.githubusercontent.com/5384543/60148002-3f00b900-9784-11e9-8e07-d415e626802e.png">

- [x]  Update "learn More" link in the "Turn your code and software development data into actionable insights" section to point to https://landing-staging.srcd.run/products/community-edition/ instead

- [x]  Update "learn More" link in the "source{d} integrates with your favorite tools & platforms
" section to point to https://landing-staging.srcd.run/products/enterprise-edition/ instead

- [x]  Update "Event" section link to point to Event anchor link https://sourced.tech/community/#events

## Header & Footer

- [x]  Update "Products" drop down menu in header to "source{d} Community Edition" and "source{d} Enterprise Edition"
<img width="307" alt="Screen Shot 2019-06-25 at 8 07 26 PM" src="https://user-images.githubusercontent.com/5384543/60148963-e92e1000-9787-11e9-88a3-c91d3118dc49.png">

- [x] https://landing-staging.srcd.run/solutions/talent-assessment-and-management is 404

## Get Started Developer Tab: 

- [x]  Update "download source{d} Link" to https://go.sourced.tech/community-edition-download

## Get Started Manager tab: 

- [x]  Update "download source{d} Link" to https://go.sourced.tech/community-edition-download

- [x]  Update "Request a demo" button text to "Request CE demo"

- [x] Update "sign up for a trial" button text to "Request EE demo" and point to enterprise edition anchor link https://landing-staging.srcd.run/products/enterprise-edition/#enterprise-demo

## Get Started Executive tab

- [x] Update "sign up for a trial" button text to "Request EE demo" and point to enterprise edition anchor link https://landing-staging.srcd.run/products/enterprise-edition/#enterprise-demo

## Resources page

- [x] Replace dog photo under source{d} Forum to
<img width="812" alt="forum" src="https://user-images.githubusercontent.com/5384543/60149143-96088d00-9788-11e9-872f-ee47337383ef.png">

## Open Source:

- [x] Remove buttons in screenshot below
<img width="476" alt="Screen Shot 2019-06-25 at 7 58 33 PM" src="https://user-images.githubusercontent.com/5384543/60147818-aec27400-9783-11e9-836c-b42a65814989.png">

- [x] Remove source{d} Engine and Newsletter section at the bottom of the page

## Company page:

- [x] See https://github.com/src-d/landing/issues/414

**Comment by znegrin** [comment]
All issues are now solved on their respective PRs: #402, #405, #423, #425, #426, #427 and #428

**Comment by dpordomingo** [comment]
@vcoisne the links "Request a Demo" at [enterprise edition](https://landing-staging.srcd.run/products/enterprise-edition/#trial) redirects to the HP with no way to ask for a demo. 
Imho it should be considered a major problem to be solved before the release.

![image](https://user-images.githubusercontent.com/2437584/60174124-a6fce100-9810-11e9-9008-f35342fed9c4.png)

note to @znegrin:
It could be related to the `<base href>` that we currently have.
I'm not sure if it can be removed if you're not sure yet, and it's blocker I could try with an absolute link to avoid the `base` directive.

**Comment by znegrin** [comment]
@dpordomingo I had no idea of how the links work, so probably is my fault as I just want to point to the `#trial` id at the bottom of the page. Can you explain me how to do that? Thanks

**Comment by vcoisne** [comment]
@znegrin @dpordomingo Yes the link should point to the "request a demo" section at the bottom of the Enterprise page. If that's not possible you can also point to https://go.sourced.tech/enterprise-demo

**Comment by dpordomingo** [comment]
I think that it would be solved if you replace the links to the anchors, with urls relative to the `base` tag used in landing, e.g.
`href="/products/enterprise-edition#trial"` instead of the current `href="#trial"`

**Comment by vcoisne** [comment]
Thank you @znegrin and @dpordomingo  

I have marked the issues that are resolved from the list above as checked. Please fix the ones that are not checked. 

Here is another one I just came accross:

[source{d} - source{d} Enterprise Edition](https://landing-staging.srcd.run/products/enterprise-edition/)

## Enterprise Edition Page

- [ ]  Text under IT Modernization needs to be updated to “With source{d} you can easily measure the amount of technical debt you have across your entire codebase as well as progress made to get rid of it. From outdated programming languages to legacy systems and deprecated libraries, all enterprises are investing in IT modernization but not all of them succeed. Source{d} not only increases your chance of success but also helps you save a lot of time in the process. Give your engineers the insights they need to be freed from their maintenance burden that affects your customers' experience.”

**Comment by znegrin** [comment]
> @vcoisne the links "Request a Demo" at [enterprise edition](https://landing-staging.srcd.run/products/enterprise-edition/#trial) redirects to the HP with no way to ask for a demo.
> Imho it should be considered a major problem to be solved before the release.
> 
> ![image](https://user-images.githubusercontent.com/2437584/60174124-a6fce100-9810-11e9-9008-f35342fed9c4.png)
> 
> note to @znegrin:
> It could be related to the `<base href>` that we currently have.
> I'm not sure if it can be removed if you're not sure yet, and it's blocker I could try with an absolute link to avoid the `base` directive.

This is now fixed on #410

**Comment by znegrin** [comment]
I think now all of the issues that were left are ready to be reviewed on their PRs.

**Comment by vcoisne** [comment]
- [ ] @znegrin Per our discussion just now, the "Request a demo" on the solutions pages should point to https://landing-staging.srcd.run/products/enterprise-edition/#trial instead of https://go.sourced.tech/engine

**Comment by vcoisne** [comment]
We're live!
