### ISSUE TITLE
Missing images in solutions

### ISSUE THREAD

**Issue by dpordomingo** [src-d/landing#431]
Two images are missing, so their sections were commented.

Whenever they are ready, `master` should be updated this way:

https://landing-staging.srcd.run/solutions/it-modernization-and-compliance/
- uncomment: [hugo/layouts/solutions/it-modernization-and-compliance/single.html#L88](https://github.com/src-d/landing/blob/06c533dcc4d3a29aec150962264fe6fabae32106/hugo/layouts/solutions/it-modernization-and-compliance/single.html#L88)
- and commit the image as: `static/img/it-modernization-2.jpg`

https://landing-staging.srcd.run/solutions/talent-assessment-and-management/
- uncomment: [hugo/layouts/solutions/talent-assessment-and-management/single.html#L40](https://github.com/src-d/landing/blob/06c533dcc4d3a29aec150962264fe6fabae32106/hugo/layouts/solutions/talent-assessment-and-management/single.html#L40)
- and commit the image as: `static/img/talent-1.jpg`

**Comment by znegrin** [comment]
@dpordomingo I just made the changes on master. Please let me know if anything else is missed. Thank you.
