### ISSUE TITLE
List of current issues to fix in production

### ISSUE THREAD

**Issue by Nicholas-Nord** [src-d/landing#435]
## Enterprise edition page

- [ ] Under  "Talent Assessment & Management" the "learn more" button currently point to a "404 Not Found" instead of https://sourced.tech/solutions/talent-assessment-and-management/ (missing an s at assessment) 

## Community edition page

- [ ]  Update the "download source{d}" button to link to https://go.sourced.tech/community-edition-download instead of https://go.sourced.tech/engine-download

## Manager get started tab 

- [ ] Update the "Request CE demo" link to point to https://go.sourced.tech/community-demo 

## Executives get started tab 

- [ ] Replace the "1m video" by "Watch 1m Video" and update the title in the pop up title to "source{d}: The Data Platform for your Software Development Life Cycle' 

## IT Modernization & Compliance

- [ ]  Update ALL the "download source{d}" buttons to link to https://go.sourced.tech/community-edition-download instead of https://go.sourced.tech/engine-download

## DevOps & Cloud Native Transformation

- [ ]  Update ALL the "download source{d}" buttons to link to https://go.sourced.tech/community-edition-download instead of https://go.sourced.tech/engine-download

## Engineering Effectiveness & Efficiency

- [ ]  Update ALL the "download source{d}" buttons to link to https://go.sourced.tech/community-edition-download instead of https://go.sourced.tech/engine-download

## Talent Assesment & Management

- [ ]  Update ALL the "download source{d}" buttons to link to https://go.sourced.tech/community-edition-download instead of https://go.sourced.tech/engine-download

## Header & Footer

- [ ] Under Company, remove About from both Header and Footer
- [ ] Replace "Team" by "Management"
- [ ] Careers links to "offices" it's of Openings

**Comment by znegrin** [comment]
I fixed all these requests on #441
