### ISSUE TITLE
List of minor website updates 

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#444]
## source{d} Community Edition page
- [ ]  Replace the "Request Demo" button by "Forum" link to forum.sourced.tech

## Manager get started tab
- [ ]  Replace the "Request CE demo" by "Watch 5m video" pointing to https://www.youtube.com/watch?v=p1sZ_-P6FxA

## Header & Footer
- [ ] Add "Careers" in both the  header drop-down menu and footer (sorry If the comment in https://github.com/src-d/landing/issues/435 was not clear. The link was the issue)

**Comment by znegrin** [comment]
@vcoisne where should the Careers link point to?? Thanks.

**Comment by dpordomingo** [comment]
Not 100% sure, but I'd say that it should be an anchor to `Worldwide Opportunities` in https://sourced.tech/company

**Comment by vcoisne** [comment]
@znegrin Looks good as is in production. Thank you
