### ISSUE TITLE
Add Slack icon back to community page

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#454]
I did not realize that we removed the Slack logo from the list of social media channels below on the community page. Could you please add it back @znegrin and link to https://sourced-community.slack.com/join/shared_invite/enQtMjc4Njk5MzEyNzM2LTFjNzY4NjEwZGEwMzRiNTM4MzRlMzQ4MmIzZjkwZmZlM2NjODUxZmJjNDI1OTcxNDAyMmZlNmFjODZlNTg0YWM

<img width="999" alt="Screen Shot 2019-07-18 at 2 56 01 PM" src="https://user-images.githubusercontent.com/5384543/61459149-62c2b380-a96c-11e9-8f2f-02682291dd4f.png">

**Comment by znegrin** [comment]
This is now on production: [v4.17.10](https://github.com/src-d/landing/releases/tag/v4.17.10)
