### ISSUE TITLE
Press Page updates

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#460]
On the Press page - https://sourced.tech/news-and-press/

1. Please move the press release list under the Analyst report section 

2. add the TechCrunch Logo linking to https://techcrunch.com/2019/07/02/software-development-analytics-platform-sourced-launches-an-enterprise-edition/

**Comment by znegrin** [comment]
This is now ready on this PR: https://github.com/src-d/landing/pull/461

**Comment by vcoisne** [comment]
@znegrin reviewed and merged. Ready for prod.

**Comment by vcoisne** [comment]
Deployed to prod. closing
