### ISSUE TITLE
Styling of consent field in pardot forms

### ISSUE THREAD

**Issue by vcoisne** [src-d/landing#465]
I'm having issues with styling the consent field in our pardot forms as you can see below

<img width="437" alt="Screen Shot 2019-09-26 at 3 26 30 PM" src="https://user-images.githubusercontent.com/5384543/65729325-b93a2580-e072-11e9-9ef5-b88226f95332.png">

I think it has to do with our form layout. Could you please take a look @ricardobaeta ?

**Comment by ricardobaeta** [comment]
HI @vcoisne ! I took a look at Pardot, but wasn't able to find this specific Form. Could you point me out to it, please?

**Comment by ricardobaeta** [comment]
@vcoisne Not only this form/checkbox is properly styled now, but as well all the forms inherited by the "Product Landing Page Template" are now being styled accordingly.

![image](https://user-images.githubusercontent.com/1746146/66001169-e0408f00-e498-11e9-8077-e6f6ff5ed4c0.png)
   
You might want to close this per objective accomplishment.

**Comment by vcoisne** [comment]
Nice job @ricardobaeta thanks!
