### ISSUE TITLE
Slackin Dockerfile is broken

### ISSUE THREAD

**Issue by rporres** [src-d/landing#62]
Currently slackin needs reCAPTCHA configuration as per https://github.com/rauchg/slackin/pull/311

If we want our current Dockerfile to work we need to checkout a previous version of Slackin. Adding 
```
RUN git checkout 3ff77b9
```
before https://github.com/src-d/landing/blob/master/Dockerfile.slackin#L15 does the trick unless we want to use the last Slackin version with reCAPTCHA integration (which would need further work)

Let me know if you want a PR containing the above change.

**Comment by erizocosmico** [comment]
I guess we should upgrade then and provide a reCAPTCHA key?

**Comment by rporres** [comment]
Current workaround in https://github.com/src-d/landing/blob/master/Dockerfile.slackin#L16 (checkout `0.13.1`)

Apparently we don't have space in landing for CAPTCHAs, so we don't use it for the moment
