### ISSUE TITLE
quay.io/srcd/landing:slackin image comes from a landing docker build, not a slackin

### ISSUE THREAD

**Issue by rporres** [src-d/landing#66]
As an example
```
docker pull quay.io/srcd/landing:slackin
docker run --restart always -d -p 3000:3000 --name landing-SLACKIN -e SLACK_API_TOKEN=TOKEN quay.io/srcd/landing:slackin
docker exec -it landing-SLACKIN sh
/srv # netstat -na | grep LISTEN
tcp        0      0 :::8080                 :::*                    LISTEN
tcp        0      0 :::8090                 :::*                    LISTEN
/srv # ps -ef
PID   USER     TIME   COMMAND
    1 root       0:03 {supervisord} /usr/bin/python /usr/bin/supervisord
    9 root       0:00 /bin/api -config /etc/production.yaml
   10 root       0:00 /usr/bin/caddy --conf /etc/Caddyfile --log stdout
   24 root       0:00 sh
   36 root       0:00 sh
   46 root       0:00 ps -ef
```

**Comment by erizocosmico** [comment]
Must have pushed the wrong image back when we were updating the thing. We need to update it to the last version, anyway.

**Comment by Serabe** [comment]
Please, don't update slackin, we don't have space in the design for the new recaptcha thingy :(

**Comment by erizocosmico** [comment]
Didn't update it in the end. It uses the previous version.

**Comment by marnovo** [comment]
@dpordomingo just talk to @rporres to see what was the exact problem and if it's solvable by not updating our slackin until we find a workaround.

**Comment by rporres** [comment]
I will upload the image running in prod to quay

**Comment by dpordomingo** [comment]
@marnovo, as clarified with @rporres this issue affects only to the current landing in production (if the current production machine losts its data, there would be no way to recover the slackin image).

This problem does not exist in the Production environment that we are about to use, nor in Staging as we are currently using.

To avoid problems with Production before migrating the landing to the new infrastructure, Rafa is pushing the right image to Quay as he said in the previous comment.

**Comment by rporres** [comment]
uploaded
