### ISSUE TITLE
Separate Landing and API processes

### ISSUE THREAD

**Issue by rporres** [src-d/landing#67]
Currently they live in the same Docker container which is not the best practise por Docker containers. It also needs Caddy to act as a reverse proxy. It makes the deployment in k8s rather obscure.

Once this is done, the Caddy config can be simplified removing the proxy parts once the [landing helm chart](https://github.com/src-d/charts/tree/master/landing) ingress template is configured properly

**Comment by Serabe** [comment]
Closed by #71
