### ISSUE TITLE
quay.io images should not be private

### ISSUE THREAD

**Issue by rporres** [src-d/landing#72]
Taken into account that this is not a private repo

**Comment by smeruelo** [comment]
Our licence with quay gives us 50 private repositories, and we already have 46 in use. If the repo at github is public, I'd say the images at quay could be too.

**Comment by erizocosmico** [comment]
That's a thing for you guys, we can't change stuff in quay.

**Comment by smeruelo** [comment]
I'll make the quay repos public if you give the go-ahead.

**Comment by erizocosmico** [comment]
@mcuadros @Serabe

**Comment by Serabe** [comment]
This is for @mcuadros.

**Comment by Serabe** [comment]
@mcuadros ping

**Comment by rporres** [comment]
Repos are public hence these images need to be public. I will take care of this
