### ISSUE TITLE
Add media queries for adjustments in menues.

### ISSUE THREAD

**Issue by Serabe** [src-d/landing#92]
We need to adjust the menu for some custom breakpoints.
![2017-07-26 at 13 30](https://user-images.githubusercontent.com/36221/28618961-a7682ad2-7206-11e7-9b5e-7309861f8b20.png)

**Comment by erizocosmico** [comment]
Isn't that already https://github.com/src-d/backlog/issues/928?

**Comment by marnovo** [comment]
@dpordomingo let's review this after the `stack` section removed.

**Comment by dpordomingo** [comment]
It will reviewed again considering https://github.com/src-d/landing/pull/141

**Comment by dpordomingo** [comment]
@marnovo I could not reproduce the error.

Desktop 1500px
![image](https://user-images.githubusercontent.com/2437584/29924750-46fb9868-8e5e-11e7-83fb-6992448c3536.png)

Desktop 1200px
![image](https://user-images.githubusercontent.com/2437584/29924819-8bc959ee-8e5e-11e7-8d84-3c3228f52ca6.png)

Desktop 1280px
![image](https://user-images.githubusercontent.com/2437584/29924835-9dc22aea-8e5e-11e7-8bcf-2a68aa550963.png)

Dektop 992px
![image](https://user-images.githubusercontent.com/2437584/29924863-bafc5428-8e5e-11e7-9bd9-e40b2c3307ed.png)

Ipad 768px
![image](https://user-images.githubusercontent.com/2437584/29924937-fc25fc9c-8e5e-11e7-82e0-9adc0050377f.png)

Iphone 6+ 414px
![image](https://user-images.githubusercontent.com/2437584/29925050-6ba4b356-8e5f-11e7-8d80-6c0a4e23a3c2.png)
